//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v11.4.1+29f8f0b
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace DffEdb.Umb.Models
{
	/// <summary>Beskeder</summary>
	[PublishedModel("Beskeder")]
	public partial class Beskeder : PublishedContentModel, IMaster
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		public new const string ModelTypeAlias = "Beskeder";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<Beskeder, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Beskeder(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Beskrivende tekst til individuel: Individuel tekst
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("AfkoelingIndividuelTekst")]
		public virtual string AfkoelingIndividuelTekst => this.Value<string>(_publishedValueFallback, "AfkoelingIndividuelTekst");

		///<summary>
		/// Individuel
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("AfkoelingIndividuelValg")]
		public virtual bool AfkoelingIndividuelValg => this.Value<bool>(_publishedValueFallback, "AfkoelingIndividuelValg");

		///<summary>
		/// AfkoelingOverskrift
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("AfkoelingOverskrift")]
		public virtual object AfkoelingOverskrift => this.Value(_publishedValueFallback, "AfkoelingOverskrift");

		///<summary>
		/// Beskrivende tekst til standard
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("AfkoelingStandardTekst")]
		public virtual string AfkoelingStandardTekst => this.Value<string>(_publishedValueFallback, "AfkoelingStandardTekst");

		///<summary>
		/// Standard
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("AfkoelingStandardValg")]
		public virtual bool AfkoelingStandardValg => this.Value<bool>(_publishedValueFallback, "AfkoelingStandardValg");

		///<summary>
		/// Afkøling undertekst: Beskrivende tekst til afkøling
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("afkoelingUndertekst")]
		public virtual string AfkoelingUndertekst => this.Value<string>(_publishedValueFallback, "afkoelingUndertekst");

		///<summary>
		/// BeskedTyper: Få besked på
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("BeskedTyper")]
		public virtual object BeskedTyper => this.Value(_publishedValueFallback, "BeskedTyper");

		///<summary>
		/// Beskrivelse
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("beskrivelseBesked")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString BeskrivelseBesked => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "beskrivelseBesked");

		///<summary>
		/// Dag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("dag")]
		public virtual bool Dag => this.Value<bool>(_publishedValueFallback, "dag");

		///<summary>
		/// Beskrivende tekst til individuel
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ForbrugIndividuelTekst")]
		public virtual string ForbrugIndividuelTekst => this.Value<string>(_publishedValueFallback, "ForbrugIndividuelTekst");

		///<summary>
		/// Individuel
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("ForbrugIndividuelValg")]
		public virtual bool ForbrugIndividuelValg => this.Value<bool>(_publishedValueFallback, "ForbrugIndividuelValg");

		///<summary>
		/// ForbrugsOverskrift
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ForbrugOverskrift")]
		public virtual object ForbrugOverskrift => this.Value(_publishedValueFallback, "ForbrugOverskrift");

		///<summary>
		/// Beskrivende tekst til standard
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ForbrugStandardTekst")]
		public virtual string ForbrugStandardTekst => this.Value<string>(_publishedValueFallback, "ForbrugStandardTekst");

		///<summary>
		/// Standard
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("ForbrugStandardValg")]
		public virtual bool ForbrugStandardValg => this.Value<bool>(_publishedValueFallback, "ForbrugStandardValg");

		///<summary>
		/// Forbrug undertekst: Overordnet beskrivende tekst
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ForbrugUndertekst")]
		public virtual string ForbrugUndertekst => this.Value<string>(_publishedValueFallback, "ForbrugUndertekst");

		///<summary>
		/// FrekvensOverskrift: udbyder
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("FrekvensOverskrift")]
		public virtual object FrekvensOverskrift => this.Value(_publishedValueFallback, "FrekvensOverskrift");

		///<summary>
		/// Måned
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("maaned")]
		public virtual bool Maaned => this.Value<bool>(_publishedValueFallback, "maaned");

		///<summary>
		/// e-mail: Skal forbrugerne kunne vælge at modtage besked via e-mail?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("mailbesked")]
		public virtual bool Mailbesked => this.Value<bool>(_publishedValueFallback, "mailbesked");

		///<summary>
		/// Overskrift
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("overskriftBesked")]
		public virtual string OverskriftBesked => this.Value<string>(_publishedValueFallback, "overskriftBesked");

		///<summary>
		/// Beskrivende tekst til individuel
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ReturIndividuelTekst")]
		public virtual string ReturIndividuelTekst => this.Value<string>(_publishedValueFallback, "ReturIndividuelTekst");

		///<summary>
		/// Individuel
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("ReturIndividuelValg")]
		public virtual bool ReturIndividuelValg => this.Value<bool>(_publishedValueFallback, "ReturIndividuelValg");

		///<summary>
		/// ReturOverskrift: Vreturtemperatur
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ReturOverskrift")]
		public virtual object ReturOverskrift => this.Value(_publishedValueFallback, "ReturOverskrift");

		///<summary>
		/// Beskrivende tekst til standard
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ReturStandardTekst")]
		public virtual string ReturStandardTekst => this.Value<string>(_publishedValueFallback, "ReturStandardTekst");

		///<summary>
		/// Standard
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("ReturStandardValg")]
		public virtual bool ReturStandardValg => this.Value<bool>(_publishedValueFallback, "ReturStandardValg");

		///<summary>
		/// Retur undertekst: Beskrivende tekst til returtemperatur
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ReturUndertekst")]
		public virtual string ReturUndertekst => this.Value<string>(_publishedValueFallback, "ReturUndertekst");

		///<summary>
		/// SideOverskrift: test
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("SideOverskrift")]
		public virtual object SideOverskrift => this.Value(_publishedValueFallback, "SideOverskrift");

		///<summary>
		/// SMS: Skal forbrugerne kunne vælge at modtage besked via SMS?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("smsBesked")]
		public virtual bool SmsBesked => this.Value<bool>(_publishedValueFallback, "smsBesked");

		///<summary>
		/// Uge
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("uge")]
		public virtual bool Uge => this.Value<bool>(_publishedValueFallback, "uge");

		///<summary>
		/// Overvågning af afkøling
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("visAfkoeling")]
		public virtual bool VisAfkoeling => this.Value<bool>(_publishedValueFallback, "visAfkoeling");

		///<summary>
		/// Overvågning af forbrug
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("visForbrug")]
		public virtual bool VisForbrug => this.Value<bool>(_publishedValueFallback, "visForbrug");

		///<summary>
		/// Overvågning af returtemperatur
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("visReturtemperatur")]
		public virtual bool VisReturtemperatur => this.Value<bool>(_publishedValueFallback, "visReturtemperatur");

		///<summary>
		/// Menu Tekst
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("menuTekst")]
		public virtual string MenuTekst => global::DffEdb.Umb.Models.Master.GetMenuTekst(this, _publishedValueFallback);

		///<summary>
		/// Skjul i menu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("umbracoNaviHide")]
		public virtual bool UmbracoNaviHide => global::DffEdb.Umb.Models.Master.GetUmbracoNaviHide(this, _publishedValueFallback);
	}
}
