//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v11.4.1+29f8f0b
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace DffEdb.Umb.Models
{
	/// <summary>eForsyning</summary>
	[PublishedModel("eforsyning")]
	public partial class Eforsyning : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		public new const string ModelTypeAlias = "eforsyning";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<Eforsyning, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Eforsyning(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// App Server Uri: Uri til værkets App Server
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("appServerUri")]
		public virtual string AppServerUri => this.Value<string>(_publishedValueFallback, "appServerUri");

		///<summary>
		/// Box indhold 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("boxIndhold1")]
		public virtual string BoxIndhold1 => this.Value<string>(_publishedValueFallback, "boxIndhold1");

		///<summary>
		/// Box indhold 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("boxIndhold2")]
		public virtual string BoxIndhold2 => this.Value<string>(_publishedValueFallback, "boxIndhold2");

		///<summary>
		/// Box indhold 3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("boxIndhold3")]
		public virtual string BoxIndhold3 => this.Value<string>(_publishedValueFallback, "boxIndhold3");

		///<summary>
		/// Brug redirect: Hvis E|Forsyning skal omdirigeres til en anden side.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("brugRedirect")]
		public virtual bool BrugRedirect => this.Value<bool>(_publishedValueFallback, "brugRedirect");

		///<summary>
		/// Firmanavn: Angiv firmanavn. Dette firmanavn udstilles på værksliste i appen.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("eforsyningFirmanavn")]
		public virtual string EforsyningFirmanavn => this.Value<string>(_publishedValueFallback, "eforsyningFirmanavn");

		///<summary>
		/// Forsyningsid
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("forsyningId")]
		public virtual string ForsyningId => this.Value<string>(_publishedValueFallback, "forsyningId");

		///<summary>
		/// Google Analytics 4: Format: G-xxxxxxxxxx  Indsæt Google Analytics 4 sporings-id, som gælder specifikt for denne E|Forsyning
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ga4MeasurementId")]
		public virtual string Ga4MeasurementId => this.Value<string>(_publishedValueFallback, "ga4MeasurementId");

		///<summary>
		/// Google Universal Analytics (udgår): Format: UA-xxxxxxxxxx  Indsæt Universal Analytics sporings-id, som gælder specifikt for denne E|Forsyning
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("googleAnalytics")]
		public virtual string GoogleAnalytics => this.Value<string>(_publishedValueFallback, "googleAnalytics");

		///<summary>
		/// Kontaktoplysninger: Viser en popup, hvor vi spørger om aktuelle e-mail og telefonnummer er korrekte.  Kampagnen vises hver tredje måned.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("kontaktoplysningerKampagne")]
		public virtual bool KontaktoplysningerKampagne => this.Value<bool>(_publishedValueFallback, "kontaktoplysningerKampagne");

		///<summary>
		/// Menunavn: Navnet på e|forsyning i menuen, Hvis denne er blank vil 'Min side' blive brugt.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("menuNavn")]
		public virtual string MenuNavn => this.Value<string>(_publishedValueFallback, "menuNavn");

		///<summary>
		/// Overskrift på loginsiden: Overskrift på loginside. Hvis denne er blank vil der stå "E|Forsyning"
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("overskriftPaaLoginside")]
		public virtual string OverskriftPaaLoginside => this.Value<string>(_publishedValueFallback, "overskriftPaaLoginside");

		///<summary>
		/// Redirect Side: Brug hele URL'en f.eks. http://forsyninger.dk/nyheder.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("redirectSide")]
		public virtual string RedirectSide => this.Value<string>(_publishedValueFallback, "redirectSide");

		///<summary>
		/// Farvetema
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tema")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent Tema => this.Value<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent>(_publishedValueFallback, "tema");

		///<summary>
		/// Skjul i menu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("umbracoNaviHide")]
		public virtual bool UmbracoNaviHide => this.Value<bool>(_publishedValueFallback, "umbracoNaviHide");
	}
}
