//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v11.4.1+29f8f0b
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace DffEdb.Umb.Models
{
	/// <summary>Leveres fjernvarme Widget</summary>
	[PublishedModel("forsyningPaaAdresse")]
	public partial class ForsyningPaaAdresse : PublishedContentModel, IWebComponentHtml
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		public new const string ModelTypeAlias = "forsyningPaaAdresse";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<ForsyningPaaAdresse, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public ForsyningPaaAdresse(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Afgræns til specifikke postnumre: Du har her mulighed for at afgrænse adressesøgningen til specifikke postnumre
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("afgraensningOverskrift")]
		public virtual string AfgraensningOverskrift => this.Value<string>(_publishedValueFallback, "afgraensningOverskrift");

		///<summary>
		/// Postnumre: Ét postnummer pr. linje.  Hvis du ikke angiver postnumre, søger vi i hele Danmark.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("afgraensningPostNr")]
		public virtual string AfgraensningPostNr => this.Value<string>(_publishedValueFallback, "afgraensningPostNr");

		///<summary>
		/// E|Forsyning: Vælg hvilken E|Forsyning der skal kaldes for at undersøge om der leveres fjernvarme til en given adresse
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("eforsyningNodeId")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent EforsyningNodeId => this.Value<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent>(_publishedValueFallback, "eforsyningNodeId");

		///<summary>
		/// Vælg E|Forsyning: For at kunne undersøge om der leveres fjernvarme til en bestemt adresse, har vi behov for at lave opslag i FOF. Du skal derfor vælge en E|Forsyning, som har adgang til FOF.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("eforsyningOverskrift")]
		public virtual string EforsyningOverskrift => this.Value<string>(_publishedValueFallback, "eforsyningOverskrift");

		///<summary>
		/// Svarmuligheder: Nedenfor kan du angive hvilken tekst forbrugeren skal have vist, afhængig af om vi leverer fjernvarme til adressen eller ej
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("svarmulighederOverskrift")]
		public virtual string SvarmulighederOverskrift => this.Value<string>(_publishedValueFallback, "svarmulighederOverskrift");

		///<summary>
		/// Ja: Skriv tekst som skal vises, hvis der leveres fjernvarme til adressen
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("svarmulighedJa")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString SvarmulighedJa => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "svarmulighedJa");

		///<summary>
		/// Nej: Skriv tekst som skal vises, hvis der ikke levers fjernvarme til adressen
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("svarmulighedNej")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString SvarmulighedNej => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "svarmulighedNej");

		///<summary>
		/// Planlagt: Skriv tekst som skal vises, hvis der endnu ikke levers fjernvarme til adressen, men der er planer om det i nær fremtid
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("svarmulighedPlanlagt")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString SvarmulighedPlanlagt => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "svarmulighedPlanlagt");

		///<summary>
		/// HTML: HTML til at indsætte på ekstern hjemmeside. Dvs. side, som ikke er hostet hos os.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("html")]
		public virtual global::Newtonsoft.Json.Linq.JToken Html => global::DffEdb.Umb.Models.WebComponentHtml.GetHtml(this, _publishedValueFallback);
	}
}
