//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v11.4.1+29f8f0b
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace DffEdb.Umb.Models
{
	/// <summary>Frontpage</summary>
	[PublishedModel("frontpage")]
	public partial class Frontpage : PublishedContentModel, IInfoPopup, ISeo
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		public new const string ModelTypeAlias = "frontpage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<Frontpage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Frontpage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Antal nyheder: Hvor mange nyheder skal vises på topbilledet?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("antalNyheder")]
		public virtual string AntalNyheder => this.Value<string>(_publishedValueFallback, "antalNyheder");

		///<summary>
		/// Bannertekst
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bannertekstGroupLabel")]
		public virtual string BannertekstGroupLabel => this.Value<string>(_publishedValueFallback, "bannertekstGroupLabel");

		///<summary>
		/// Indhold
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bodyText")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockGridModel BodyText => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockGridModel>(_publishedValueFallback, "bodyText");

		///<summary>
		/// Element margin: Vælg hvor meget luft der skal være til højre og venstre i tekstbaserede elementer
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("elementMargin")]
		public virtual string ElementMargin => this.Value<string>(_publishedValueFallback, "elementMargin");

		///<summary>
		/// Grid
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("footerGrid")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockGridModel FooterGrid => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockGridModel>(_publishedValueFallback, "footerGrid");

		///<summary>
		/// Google Analytics 4: Format: G-xxxxxxxxxx  Indsæt Google Analytics 4 sporings-id, som gælder specifikt for hjemmesiden
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ga4MeasurementId")]
		public virtual string Ga4MeasurementId => this.Value<string>(_publishedValueFallback, "ga4MeasurementId");

		///<summary>
		/// Google Universal Analytics (udgår): Format: UA-xxxxxxxxxx  Indsæt Universal Analytics sporings-id, som gælder specifikt for hjemmesiden
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("googleAnalytics")]
		public virtual string GoogleAnalytics => this.Value<string>(_publishedValueFallback, "googleAnalytics");

		///<summary>
		/// Billedehøjde
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("imageHeight")]
		public virtual string ImageHeight => this.Value<string>(_publishedValueFallback, "imageHeight");

		///<summary>
		/// Billedhøjde
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("imageHeightContent")]
		public virtual string ImageHeightContent => this.Value<string>(_publishedValueFallback, "imageHeightContent");

		///<summary>
		/// Start: Hvornår skal popup'en vises?  Kan efterlades blank, hvis den skal vises allerede nu.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("infoPopupTidsstyringFra")]
		public virtual global::System.DateTime InfoPopupTidsstyringFra => this.Value<global::System.DateTime>(_publishedValueFallback, "infoPopupTidsstyringFra");

		///<summary>
		/// Tidsstyring: Hvornår skal popup'en vises?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("infoPopupTidsstyringH3")]
		public virtual string InfoPopupTidsstyringH3 => this.Value<string>(_publishedValueFallback, "infoPopupTidsstyringH3");

		///<summary>
		/// Slut: Hvornår skal popup'en ikke længere vises?  Kan efterlades blank, hvis der ikke er noget udløbstidspunkt.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("infoPopupTidsstyringTil")]
		public virtual global::System.DateTime InfoPopupTidsstyringTil => this.Value<global::System.DateTime>(_publishedValueFallback, "infoPopupTidsstyringTil");

		///<summary>
		/// Inverter tekst (standard topbillede): Hvid tekst istedet for sort - Har ingen effekt hvis sidetitel ikke vises
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("inverterBannerTekst")]
		public virtual bool InverterBannerTekst => this.Value<bool>(_publishedValueFallback, "inverterBannerTekst");

		///<summary>
		/// Inverter bannertekst
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("inverterForsideBannerTekst")]
		public virtual bool InverterForsideBannerTekst => this.Value<bool>(_publishedValueFallback, "inverterForsideBannerTekst");

		///<summary>
		/// Layout
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("layout")]
		public virtual string Layout => this.Value<string>(_publishedValueFallback, "layout");

		///<summary>
		/// Layout
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("layoutSeperator")]
		public virtual object LayoutSeperator => this.Value(_publishedValueFallback, "layoutSeperator");

		///<summary>
		/// Overskrift
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mainText")]
		public virtual string MainText => this.Value<string>(_publishedValueFallback, "mainText");

		///<summary>
		/// Nyheder
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nyhederGroupLabel")]
		public virtual string NyhederGroupLabel => this.Value<string>(_publishedValueFallback, "nyhederGroupLabel");

		///<summary>
		/// Sidetitel i versaler: Har ingen effekt hvis sidetitel ikke vises
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("sidetitelIVersaler")]
		public virtual bool SidetitelIversaler => this.Value<bool>(_publishedValueFallback, "sidetitelIVersaler");

		///<summary>
		/// Skjul brødkummespor
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("skjulBroedkummespor")]
		public virtual bool SkjulBroedkummespor => this.Value<bool>(_publishedValueFallback, "skjulBroedkummespor");

		///<summary>
		/// Skjul nyheder i footer
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("skjulNyhederIFooter")]
		public virtual bool SkjulNyhederIfooter => this.Value<bool>(_publishedValueFallback, "skjulNyhederIFooter");

		///<summary>
		/// Søgeside
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("soegeside")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent Soegeside => this.Value<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent>(_publishedValueFallback, "soegeside");

		///<summary>
		/// Søgning
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("soegning")]
		public virtual object Soegning => this.Value(_publishedValueFallback, "soegning");

		///<summary>
		/// Lille overskrift
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("subText")]
		public virtual string SubText => this.Value<string>(_publishedValueFallback, "subText");

		///<summary>
		/// Tekst
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tekst")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString Tekst => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "tekst");

		///<summary>
		/// Topbanner (undersider)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("topBannerUndersider")]
		public virtual object TopBannerUndersider => this.Value(_publishedValueFallback, "topBannerUndersider");

		///<summary>
		/// Standard topbillede
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("topBillede")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TopBillede => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "topBillede");

		///<summary>
		/// Topbillede
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("topImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops TopImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "topImage");

		///<summary>
		/// Vælg nyhedsfeed: Vælg det feed der skal udstille nyheder.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("vaelgNyhederFeed")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent VaelgNyhederFeed => this.Value<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent>(_publishedValueFallback, "vaelgNyhederFeed");

		///<summary>
		/// Vis overlay: Skal der vises et semitransparent overlay bag teksten?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("visOverlay")]
		public virtual bool VisOverlay => this.Value<bool>(_publishedValueFallback, "visOverlay");

		///<summary>
		/// Vis sidetitel
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("visSidetitel")]
		public virtual bool VisSidetitel => this.Value<bool>(_publishedValueFallback, "visSidetitel");

		///<summary>
		/// Knap
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("infoPopupButtonH3")]
		public virtual string InfoPopupButtonH3 => global::DffEdb.Umb.Models.InfoPopup.GetInfoPopupButtonH3(this, _publishedValueFallback);

		///<summary>
		/// Side
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("infoPopupButtonLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link InfoPopupButtonLink => global::DffEdb.Umb.Models.InfoPopup.GetInfoPopupButtonLink(this, _publishedValueFallback);

		///<summary>
		/// Tekst
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("infoPopupButtonText")]
		public virtual string InfoPopupButtonText => global::DffEdb.Umb.Models.InfoPopup.GetInfoPopupButtonText(this, _publishedValueFallback);

		///<summary>
		/// Indhold
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("infoPopupContent")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString InfoPopupContent => global::DffEdb.Umb.Models.InfoPopup.GetInfoPopupContent(this, _publishedValueFallback);

		///<summary>
		/// Ventetider
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("infoPopupDelayH3")]
		public virtual string InfoPopupDelayH3 => global::DffEdb.Umb.Models.InfoPopup.GetInfoPopupDelayH3(this, _publishedValueFallback);

		///<summary>
		/// Vis popup: Skal popup vises når man besøger forsiden?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("infoPopupEnabled")]
		public virtual bool InfoPopupEnabled => global::DffEdb.Umb.Models.InfoPopup.GetInfoPopupEnabled(this, _publishedValueFallback);

		///<summary>
		/// Overskrift
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("infoPopupHeader")]
		public virtual string InfoPopupHeader => global::DffEdb.Umb.Models.InfoPopup.GetInfoPopupHeader(this, _publishedValueFallback);

		///<summary>
		/// Tid inden popup forsvinder: Hvor mange sekunder skal der gå inden popup skjules.  Default skal brugeren selv lukke den.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("infoPopupHideAfterSec")]
		public virtual int InfoPopupHideAfterSec => global::DffEdb.Umb.Models.InfoPopup.GetInfoPopupHideAfterSec(this, _publishedValueFallback);

		///<summary>
		/// Billede
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("infoPopupImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops InfoPopupImage => global::DffEdb.Umb.Models.InfoPopup.GetInfoPopupImage(this, _publishedValueFallback);

		///<summary>
		/// Tid inden popup vises: Hvor mange sekunder skal der gå inden popup vises?  Default vises den med det samme.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("infoPopupShowAfterSec")]
		public virtual int InfoPopupShowAfterSec => global::DffEdb.Umb.Models.InfoPopup.GetInfoPopupShowAfterSec(this, _publishedValueFallback);

		///<summary>
		/// Seo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("seoMetadata")]
		public virtual string SeoMetadata => global::DffEdb.Umb.Models.Seo.GetSeoMetadata(this, _publishedValueFallback);
	}
}
