//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v11.4.1+29f8f0b
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace DffEdb.Umb.Models
{
	// Mixin Content Type with alias "infoPopup"
	/// <summary>Popup</summary>
	public partial interface IInfoPopup : IPublishedContent
	{
		/// <summary>Knap</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string InfoPopupButtonH3 { get; }

		/// <summary>Side</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Models.Link InfoPopupButtonLink { get; }

		/// <summary>Tekst</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string InfoPopupButtonText { get; }

		/// <summary>Indhold</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Strings.IHtmlEncodedString InfoPopupContent { get; }

		/// <summary>Ventetider</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string InfoPopupDelayH3 { get; }

		/// <summary>Vis popup</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		bool InfoPopupEnabled { get; }

		/// <summary>Overskrift</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string InfoPopupHeader { get; }

		/// <summary>Tid inden popup forsvinder</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		int InfoPopupHideAfterSec { get; }

		/// <summary>Billede</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.Models.MediaWithCrops InfoPopupImage { get; }

		/// <summary>Tid inden popup vises</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		int InfoPopupShowAfterSec { get; }
	}

	/// <summary>Popup</summary>
	[PublishedModel("infoPopup")]
	public partial class InfoPopup : PublishedContentModel, IInfoPopup
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		public new const string ModelTypeAlias = "infoPopup";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<InfoPopup, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public InfoPopup(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Knap
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("infoPopupButtonH3")]
		public virtual string InfoPopupButtonH3 => GetInfoPopupButtonH3(this, _publishedValueFallback);

		/// <summary>Static getter for Knap</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetInfoPopupButtonH3(IInfoPopup that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "infoPopupButtonH3");

		///<summary>
		/// Side
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("infoPopupButtonLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link InfoPopupButtonLink => GetInfoPopupButtonLink(this, _publishedValueFallback);

		/// <summary>Static getter for Side</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Models.Link GetInfoPopupButtonLink(IInfoPopup that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Models.Link>(publishedValueFallback, "infoPopupButtonLink");

		///<summary>
		/// Tekst
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("infoPopupButtonText")]
		public virtual string InfoPopupButtonText => GetInfoPopupButtonText(this, _publishedValueFallback);

		/// <summary>Static getter for Tekst</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetInfoPopupButtonText(IInfoPopup that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "infoPopupButtonText");

		///<summary>
		/// Indhold
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("infoPopupContent")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString InfoPopupContent => GetInfoPopupContent(this, _publishedValueFallback);

		/// <summary>Static getter for Indhold</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Strings.IHtmlEncodedString GetInfoPopupContent(IInfoPopup that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(publishedValueFallback, "infoPopupContent");

		///<summary>
		/// Ventetider
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("infoPopupDelayH3")]
		public virtual string InfoPopupDelayH3 => GetInfoPopupDelayH3(this, _publishedValueFallback);

		/// <summary>Static getter for Ventetider</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetInfoPopupDelayH3(IInfoPopup that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "infoPopupDelayH3");

		///<summary>
		/// Vis popup: Skal popup vises når man besøger forsiden?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("infoPopupEnabled")]
		public virtual bool InfoPopupEnabled => GetInfoPopupEnabled(this, _publishedValueFallback);

		/// <summary>Static getter for Vis popup</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		public static bool GetInfoPopupEnabled(IInfoPopup that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "infoPopupEnabled");

		///<summary>
		/// Overskrift
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("infoPopupHeader")]
		public virtual string InfoPopupHeader => GetInfoPopupHeader(this, _publishedValueFallback);

		/// <summary>Static getter for Overskrift</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetInfoPopupHeader(IInfoPopup that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "infoPopupHeader");

		///<summary>
		/// Tid inden popup forsvinder: Hvor mange sekunder skal der gå inden popup skjules.  Default skal brugeren selv lukke den.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("infoPopupHideAfterSec")]
		public virtual int InfoPopupHideAfterSec => GetInfoPopupHideAfterSec(this, _publishedValueFallback);

		/// <summary>Static getter for Tid inden popup forsvinder</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		public static int GetInfoPopupHideAfterSec(IInfoPopup that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "infoPopupHideAfterSec");

		///<summary>
		/// Billede
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("infoPopupImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops InfoPopupImage => GetInfoPopupImage(this, _publishedValueFallback);

		/// <summary>Static getter for Billede</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.Models.MediaWithCrops GetInfoPopupImage(IInfoPopup that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(publishedValueFallback, "infoPopupImage");

		///<summary>
		/// Tid inden popup vises: Hvor mange sekunder skal der gå inden popup vises?  Default vises den med det samme.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("infoPopupShowAfterSec")]
		public virtual int InfoPopupShowAfterSec => GetInfoPopupShowAfterSec(this, _publishedValueFallback);

		/// <summary>Static getter for Tid inden popup vises</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		public static int GetInfoPopupShowAfterSec(IInfoPopup that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "infoPopupShowAfterSec");
	}
}
