//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v11.4.1+29f8f0b
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace DffEdb.Umb.Models
{
	/// <summary>Prisberegner Widget</summary>
	[PublishedModel("prisberegner")]
	public partial class Prisberegner : PublishedContentModel, IWebComponentHtml
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		public new const string ModelTypeAlias = "prisberegner";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<Prisberegner, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Prisberegner(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// BBR-bidrag: Du kan vælge enten at angive en fast pris pr. m² eller at benytte trappemodel, hvor prisen varierer afhængig af ejendommens areal
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fjernvarmeBbrOverskrift")]
		public virtual string FjernvarmeBbrOverskrift => this.Value<string>(_publishedValueFallback, "fjernvarmeBbrOverskrift");

		///<summary>
		/// BBR-bidrag: Pris pr. m² boligareal inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fjernvarmeBbrPriserPrM2")]
		public virtual global::System.Collections.Generic.IEnumerable<global::DffEdb.Umb.Models.TrappemodelItem> FjernvarmeBbrPriserPrM2 => this.Value<global::System.Collections.Generic.IEnumerable<global::DffEdb.Umb.Models.TrappemodelItem>>(_publishedValueFallback, "fjernvarmeBbrPriserPrM2");

		///<summary>
		/// BBR-bidrag: Pris pr. m² boligareal inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fjernvarmeBbrPrisPrM2")]
		public virtual string FjernvarmeBbrPrisPrM2 => this.Value<string>(_publishedValueFallback, "fjernvarmeBbrPrisPrM2");

		///<summary>
		/// Benyt trappemodel
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("fjernvarmeBbrTrappemodel")]
		public virtual bool FjernvarmeBbrTrappemodel => this.Value<bool>(_publishedValueFallback, "fjernvarmeBbrTrappemodel");

		///<summary>
		/// Investeringsomkostninger: Investeringsbidrag, stikledningsbidrag osv. inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fjernvarmeInvesteringsomkostninger")]
		public virtual string FjernvarmeInvesteringsomkostninger => this.Value<string>(_publishedValueFallback, "fjernvarmeInvesteringsomkostninger");

		///<summary>
		/// Med Varmemesterordning: Følgende priser benyttes i udregningen, hvis forbrugeren tilvælger Varmemesterordning
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fjernvarmeMedVarmemesterordningOverskrift")]
		public virtual string FjernvarmeMedVarmemesterordningOverskrift => this.Value<string>(_publishedValueFallback, "fjernvarmeMedVarmemesterordningOverskrift");

		///<summary>
		/// Afskrivningsperiode: Løbetid i antal år
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fjernvarmeNyUnitAfskrivningsperiodeAar")]
		public virtual string FjernvarmeNyUnitAfskrivningsperiodeAar => this.Value<string>(_publishedValueFallback, "fjernvarmeNyUnitAfskrivningsperiodeAar");

		///<summary>
		/// Køb af fjernvarmeunit: Pris for unit inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fjernvarmeNyUnitPris")]
		public virtual string FjernvarmeNyUnitPris => this.Value<string>(_publishedValueFallback, "fjernvarmeNyUnitPris");

		///<summary>
		/// Rentesats: F.eks. 4%
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fjernvarmeNyUnitRentesats")]
		public virtual string FjernvarmeNyUnitRentesats => this.Value<string>(_publishedValueFallback, "fjernvarmeNyUnitRentesats");

		///<summary>
		/// Abonnementsbidrag: Pris pr. år inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fjernvarmePrisAbonnement")]
		public virtual string FjernvarmePrisAbonnement => this.Value<string>(_publishedValueFallback, "fjernvarmePrisAbonnement");

		///<summary>
		/// Grøn omstillingsbidrag: Pris pr. m² boligareal inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fjernvarmePrisGroenOmstillingsbidrag")]
		public virtual string FjernvarmePrisGroenOmstillingsbidrag => this.Value<string>(_publishedValueFallback, "fjernvarmePrisGroenOmstillingsbidrag");

		///<summary>
		/// Energipris: Pris pr. MWh inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fjernvarmePrisPrMwh")]
		public virtual string FjernvarmePrisPrMwh => this.Value<string>(_publishedValueFallback, "fjernvarmePrisPrMwh");

		///<summary>
		/// Service og vedligehold: Pris pr. år inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fjernvarmeServiceOgVedligeholdPrAar")]
		public virtual string FjernvarmeServiceOgVedligeholdPrAar => this.Value<string>(_publishedValueFallback, "fjernvarmeServiceOgVedligeholdPrAar");

		///<summary>
		/// Tilslutningsbidrag, fast pris: Engangspris inkl. moms  Indgår ikke i månedlig pris, da der er tale om engangsydelse.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fjernvarmeTilslutningsbidragFastPris")]
		public virtual string FjernvarmeTilslutningsbidragFastPris => this.Value<string>(_publishedValueFallback, "fjernvarmeTilslutningsbidragFastPris");

		///<summary>
		/// Uden Varmemesterordning: Følgende priser benyttes i udregningen, hvis forbrugeren fravælger Varmemesterordning
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fjernvarmeUdenVarmemesterordningOverskrift")]
		public virtual string FjernvarmeUdenVarmemesterordningOverskrift => this.Value<string>(_publishedValueFallback, "fjernvarmeUdenVarmemesterordningOverskrift");

		///<summary>
		/// Valgfri felter
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fjernvarmeValgfriFelter")]
		public virtual string FjernvarmeValgfriFelter => this.Value<string>(_publishedValueFallback, "fjernvarmeValgfriFelter");

		///<summary>
		/// Varmemesterordning: Pris pr. år inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fjernvarmeVarmemesterordningPrisPrAar")]
		public virtual string FjernvarmeVarmemesterordningPrisPrAar => this.Value<string>(_publishedValueFallback, "fjernvarmeVarmemesterordningPrisPrAar");

		///<summary>
		/// Abonnement: Pris pr. år inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("natrurgasPrisAbonnementPrAar")]
		public virtual string NatrurgasPrisAbonnementPrAar => this.Value<string>(_publishedValueFallback, "natrurgasPrisAbonnementPrAar");

		///<summary>
		/// Brændværdi: kWh pr. m3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("naturgasBraendvaerdiKwhPrM3")]
		public virtual string NaturgasBraendvaerdiKwhPrM3 => this.Value<string>(_publishedValueFallback, "naturgasBraendvaerdiKwhPrM3");

		///<summary>
		/// Afskrivningsperiode: Løbetid i antal år, f.eks. 18
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("naturgasNytFyrAfskrivningsperiodeAar")]
		public virtual string NaturgasNytFyrAfskrivningsperiodeAar => this.Value<string>(_publishedValueFallback, "naturgasNytFyrAfskrivningsperiodeAar");

		///<summary>
		/// Køb af nyt gasfyr
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("naturgasNytFyrOverskrift")]
		public virtual string NaturgasNytFyrOverskrift => this.Value<string>(_publishedValueFallback, "naturgasNytFyrOverskrift");

		///<summary>
		/// Pris for nyt gasfyr: Pris inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("naturgasNytFyrPris")]
		public virtual string NaturgasNytFyrPris => this.Value<string>(_publishedValueFallback, "naturgasNytFyrPris");

		///<summary>
		/// Rentesats: F.eks. 4%
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("naturgasNytFyrRentesats")]
		public virtual string NaturgasNytFyrRentesats => this.Value<string>(_publishedValueFallback, "naturgasNytFyrRentesats");

		///<summary>
		/// Udgifter til el: Pris pr. år inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("naturgasPrisElPrAar")]
		public virtual string NaturgasPrisElPrAar => this.Value<string>(_publishedValueFallback, "naturgasPrisElPrAar");

		///<summary>
		/// Pris pr m3: Pris inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("naturgasPrisPrM3")]
		public virtual string NaturgasPrisPrM3 => this.Value<string>(_publishedValueFallback, "naturgasPrisPrM3");

		///<summary>
		/// Service og vedligehold: Pris pr. år inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("naturgasPrisServiceOgVedligeholdPrAar")]
		public virtual string NaturgasPrisServiceOgVedligeholdPrAar => this.Value<string>(_publishedValueFallback, "naturgasPrisServiceOgVedligeholdPrAar");

		///<summary>
		/// Virkningsgrad: F.eks. 90%
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("naturgasVirkningsgrad")]
		public virtual string NaturgasVirkningsgrad => this.Value<string>(_publishedValueFallback, "naturgasVirkningsgrad");

		///<summary>
		/// Virkningsgrad 0-4 år: F.eks. 97%
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("naturgasVirkningsgrad0til4Aar")]
		public virtual string NaturgasVirkningsgrad0til4Aar => this.Value<string>(_publishedValueFallback, "naturgasVirkningsgrad0til4Aar");

		///<summary>
		/// Virkningsgrad 5-8 år: F.eks. 92%
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("naturgasVirkningsgrad5til8Aar")]
		public virtual string NaturgasVirkningsgrad5til8Aar => this.Value<string>(_publishedValueFallback, "naturgasVirkningsgrad5til8Aar");

		///<summary>
		/// Virkningsgrad ældre end 8 år: F.eks. 87%
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("naturgasVirkningsgrad9tilNAar")]
		public virtual string NaturgasVirkningsgrad9tilNaar => this.Value<string>(_publishedValueFallback, "naturgasVirkningsgrad9tilNAar");

		///<summary>
		/// Giv mulighed for at vælge kedlens alder
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("naturgasVirkningsgradVaelgKedlensAlder")]
		public virtual bool NaturgasVirkningsgradVaelgKedlensAlder => this.Value<bool>(_publishedValueFallback, "naturgasVirkningsgradVaelgKedlensAlder");

		///<summary>
		/// Valgfri felter: Bruges til at estimere besparelse ved fjernvarme i forhold til olie
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("olidValgfriFelterOverskrift")]
		public virtual string OlidValgfriFelterOverskrift => this.Value<string>(_publishedValueFallback, "olidValgfriFelterOverskrift");

		///<summary>
		/// Brændværdi: kWh pr. liter
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("olieBraendvaerdiKwhPrLiter")]
		public virtual string OlieBraendvaerdiKwhPrLiter => this.Value<string>(_publishedValueFallback, "olieBraendvaerdiKwhPrLiter");

		///<summary>
		/// Elforbrug: Pris pr. år inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("olieElforbrugPrAar")]
		public virtual string OlieElforbrugPrAar => this.Value<string>(_publishedValueFallback, "olieElforbrugPrAar");

		///<summary>
		/// Afskrivningsperiode: Løbetid i antal år, f.eks. 20
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("olieNytFyrAfskrivningsperiodeAar")]
		public virtual string OlieNytFyrAfskrivningsperiodeAar => this.Value<string>(_publishedValueFallback, "olieNytFyrAfskrivningsperiodeAar");

		///<summary>
		/// Køb af nyt oliefyr
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("olieNytFyrOverskrift")]
		public virtual string OlieNytFyrOverskrift => this.Value<string>(_publishedValueFallback, "olieNytFyrOverskrift");

		///<summary>
		/// Pris for nyt oliefyr: Pris inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("olieNytFyrPris")]
		public virtual string OlieNytFyrPris => this.Value<string>(_publishedValueFallback, "olieNytFyrPris");

		///<summary>
		/// Rentesats: F.eks. 4%
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("olieNytFyrRentesats")]
		public virtual string OlieNytFyrRentesats => this.Value<string>(_publishedValueFallback, "olieNytFyrRentesats");

		///<summary>
		/// Pris pr. liter: Pris inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("oliePrisPrLiter")]
		public virtual string OliePrisPrLiter => this.Value<string>(_publishedValueFallback, "oliePrisPrLiter");

		///<summary>
		/// Service og vedligehold: Pris pr. år inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("olieServiceOgVedligeholdPrAar")]
		public virtual string OlieServiceOgVedligeholdPrAar => this.Value<string>(_publishedValueFallback, "olieServiceOgVedligeholdPrAar");

		///<summary>
		/// Skorstensfejer: Pris pr. år inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("olieSkorstensfejerPrAar")]
		public virtual string OlieSkorstensfejerPrAar => this.Value<string>(_publishedValueFallback, "olieSkorstensfejerPrAar");

		///<summary>
		/// Virkningsgrad: F.eks. 85%
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("olieVirkningsgrad")]
		public virtual string OlieVirkningsgrad => this.Value<string>(_publishedValueFallback, "olieVirkningsgrad");

		///<summary>
		/// Virkningsgrad 0-4 år: F.eks. 97%
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("olieVirkningsgrad0Til4Aar")]
		public virtual string OlieVirkningsgrad0Til4Aar => this.Value<string>(_publishedValueFallback, "olieVirkningsgrad0Til4Aar");

		///<summary>
		/// Virkningsgrad 5-8 år: F.eks. 92%
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("olieVirkningsgrad5Til8Aar")]
		public virtual string OlieVirkningsgrad5Til8Aar => this.Value<string>(_publishedValueFallback, "olieVirkningsgrad5Til8Aar");

		///<summary>
		/// Virkningsgrad ældre end 8 år: F.eks. 87%
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("olieVirkningsgrad9TilNAar")]
		public virtual string OlieVirkningsgrad9TilNaar => this.Value<string>(_publishedValueFallback, "olieVirkningsgrad9TilNAar");

		///<summary>
		/// Giv mulighed for at vælge fyrets alder
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("olieVirkningsgradVaelgFyretsAlder")]
		public virtual bool OlieVirkningsgradVaelgFyretsAlder => this.Value<bool>(_publishedValueFallback, "olieVirkningsgradVaelgFyretsAlder");

		///<summary>
		/// Abonnementsbidrag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tekstAbonnementsbidrag")]
		public virtual string TekstAbonnementsbidrag => this.Value<string>(_publishedValueFallback, "tekstAbonnementsbidrag");

		///<summary>
		/// BBR bidrag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tekstBbrBidrag")]
		public virtual string TekstBbrBidrag => this.Value<string>(_publishedValueFallback, "tekstBbrBidrag");

		///<summary>
		/// Energipris
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tekstEnergipris")]
		public virtual string TekstEnergipris => this.Value<string>(_publishedValueFallback, "tekstEnergipris");

		///<summary>
		/// Grøn omstillingsbidrag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tekstGroenOmstillingsbidrag")]
		public virtual string TekstGroenOmstillingsbidrag => this.Value<string>(_publishedValueFallback, "tekstGroenOmstillingsbidrag");

		///<summary>
		/// Investeringsomkostninger
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tekstInvesteringsomkostninger")]
		public virtual string TekstInvesteringsomkostninger => this.Value<string>(_publishedValueFallback, "tekstInvesteringsomkostninger");

		///<summary>
		/// Køb af fjernvarmeunit
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tekstKoebAfFjernvarmeunit")]
		public virtual string TekstKoebAfFjernvarmeunit => this.Value<string>(_publishedValueFallback, "tekstKoebAfFjernvarmeunit");

		///<summary>
		/// Ønsker varmemesterordning: Tekst på fra/til-knap
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tekstMedVarmemesterordning")]
		public virtual string TekstMedVarmemesterordning => this.Value<string>(_publishedValueFallback, "tekstMedVarmemesterordning");

		///<summary>
		/// Service og vedligehold
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tekstServiceOgVedligehold")]
		public virtual string TekstServiceOgVedligehold => this.Value<string>(_publishedValueFallback, "tekstServiceOgVedligehold");

		///<summary>
		/// Tilslutningsbidrag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tekstTilslutningsbidrag")]
		public virtual string TekstTilslutningsbidrag => this.Value<string>(_publishedValueFallback, "tekstTilslutningsbidrag");

		///<summary>
		/// Varmemesterordning
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tekstVarmemesterordning")]
		public virtual string TekstVarmemesterordning => this.Value<string>(_publishedValueFallback, "tekstVarmemesterordning");

		///<summary>
		/// Brændværdi: kWh pr. kg
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("traepillerBraendvaerdiKwhPrKg")]
		public virtual string TraepillerBraendvaerdiKwhPrKg => this.Value<string>(_publishedValueFallback, "traepillerBraendvaerdiKwhPrKg");

		///<summary>
		/// Elforbrug pr år: Pris pr. år inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("traepillerElforbrugPrAar")]
		public virtual string TraepillerElforbrugPrAar => this.Value<string>(_publishedValueFallback, "traepillerElforbrugPrAar");

		///<summary>
		/// Afskrivningsperiode: Løbetid i natal år f.eks. 20
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("traepillerNytFyrAfskrivningsperiodeAar")]
		public virtual string TraepillerNytFyrAfskrivningsperiodeAar => this.Value<string>(_publishedValueFallback, "traepillerNytFyrAfskrivningsperiodeAar");

		///<summary>
		/// Køb af nyt pillefyr
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("traepillerNytFyrOverskrift")]
		public virtual string TraepillerNytFyrOverskrift => this.Value<string>(_publishedValueFallback, "traepillerNytFyrOverskrift");

		///<summary>
		/// Pris for nyt pillefyr: Pris inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("traepillerNytFyrPris")]
		public virtual string TraepillerNytFyrPris => this.Value<string>(_publishedValueFallback, "traepillerNytFyrPris");

		///<summary>
		/// Rentesats: F.eks. 4%
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("traepillerNytFyrRentesats")]
		public virtual string TraepillerNytFyrRentesats => this.Value<string>(_publishedValueFallback, "traepillerNytFyrRentesats");

		///<summary>
		/// Pris pr. kg: Pris inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("traepillerPrisPrKg")]
		public virtual string TraepillerPrisPrKg => this.Value<string>(_publishedValueFallback, "traepillerPrisPrKg");

		///<summary>
		/// Service og vedligehold: Pris pr. år inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("traepillerServiceOgVedligeholdPrAar")]
		public virtual string TraepillerServiceOgVedligeholdPrAar => this.Value<string>(_publishedValueFallback, "traepillerServiceOgVedligeholdPrAar");

		///<summary>
		/// Skorstensfejer: Pris pr. år inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("traepillerSkorstensfejerPrAar")]
		public virtual string TraepillerSkorstensfejerPrAar => this.Value<string>(_publishedValueFallback, "traepillerSkorstensfejerPrAar");

		///<summary>
		/// Valgfri felter: Valgfri felter
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("traepillerValgfriFelterOverskrift")]
		public virtual string TraepillerValgfriFelterOverskrift => this.Value<string>(_publishedValueFallback, "traepillerValgfriFelterOverskrift");

		///<summary>
		/// Giv mulighed for at vælge fyrets alder
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("traepillerVgVaelgFyretsAlder")]
		public virtual bool TraepillerVgVaelgFyretsAlder => this.Value<bool>(_publishedValueFallback, "traepillerVgVaelgFyretsAlder");

		///<summary>
		/// Virkningsgrad: F.eks. 90%
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("traepillerVirkningsgrad")]
		public virtual string TraepillerVirkningsgrad => this.Value<string>(_publishedValueFallback, "traepillerVirkningsgrad");

		///<summary>
		/// Virkningsgrad 0-4 år: F.eks. 97%
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("traepillerVirkningsgrad0Til4Aar")]
		public virtual string TraepillerVirkningsgrad0Til4Aar => this.Value<string>(_publishedValueFallback, "traepillerVirkningsgrad0Til4Aar");

		///<summary>
		/// Virkningsgrad 5 til 8 år: F.eks. 92%
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("traepillerVirkningsgrad5Til8Aar")]
		public virtual string TraepillerVirkningsgrad5Til8Aar => this.Value<string>(_publishedValueFallback, "traepillerVirkningsgrad5Til8Aar");

		///<summary>
		/// Virkningsgrad over 8 år: F.eks. 87%
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("traepillerVirkningsgrad9TilNAar")]
		public virtual string TraepillerVirkningsgrad9TilNaar => this.Value<string>(_publishedValueFallback, "traepillerVirkningsgrad9TilNAar");

		///<summary>
		/// Valgfri felter: Bruges til at estimere besparelse ved fjernvarme i forhold til naturgas
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("valgfriFelter")]
		public virtual string ValgfriFelter => this.Value<string>(_publishedValueFallback, "valgfriFelter");

		///<summary>
		/// Varmekilder: Hvilke varmekilder skal kunne vælges i beregneren?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("varmekilder")]
		public virtual global::System.Collections.Generic.IEnumerable<string> Varmekilder => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "varmekilder");

		///<summary>
		/// Elpris: Pris pr kWh inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("varmepumpeElprisPrKwh")]
		public virtual string VarmepumpeElprisPrKwh => this.Value<string>(_publishedValueFallback, "varmepumpeElprisPrKwh");

		///<summary>
		/// Afskrivningsperiode: Løbetid i antal år
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("varmepumpeNyPumpeAfskrivningsperiodeAar")]
		public virtual string VarmepumpeNyPumpeAfskrivningsperiodeAar => this.Value<string>(_publishedValueFallback, "varmepumpeNyPumpeAfskrivningsperiodeAar");

		///<summary>
		/// Køb af ny varmepumpe
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("varmepumpeNyPumpeOverskrift")]
		public virtual string VarmepumpeNyPumpeOverskrift => this.Value<string>(_publishedValueFallback, "varmepumpeNyPumpeOverskrift");

		///<summary>
		/// Pris for ny varmepumpe: Pris inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("varmepumpeNyPumpePris")]
		public virtual string VarmepumpeNyPumpePris => this.Value<string>(_publishedValueFallback, "varmepumpeNyPumpePris");

		///<summary>
		/// Rentesats: F.eks. 4%
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("varmepumpeNyPumpeRentesats")]
		public virtual string VarmepumpeNyPumpeRentesats => this.Value<string>(_publishedValueFallback, "varmepumpeNyPumpeRentesats");

		///<summary>
		/// Service og vedligehold: Pris pr. år inkl. moms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("varmepumpeServiceOgVedligeholdPrAar")]
		public virtual string VarmepumpeServiceOgVedligeholdPrAar => this.Value<string>(_publishedValueFallback, "varmepumpeServiceOgVedligeholdPrAar");

		///<summary>
		/// Valgfri felter: Bruges til at estimere besparelse ved fjernvarme i forhold til varmepumpe
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("varmepumpeValgfriFelterOverskrift")]
		public virtual string VarmepumpeValgfriFelterOverskrift => this.Value<string>(_publishedValueFallback, "varmepumpeValgfriFelterOverskrift");

		///<summary>
		/// COP-værdi: F.eks. 325%
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("varmepumpeVirkningsgrad")]
		public virtual string VarmepumpeVirkningsgrad => this.Value<string>(_publishedValueFallback, "varmepumpeVirkningsgrad");

		///<summary>
		/// Vis beregningsgrundlag: Skal der vises beregningsgrundlag med mulighed for at dykke ned i detaljerne?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("visDetaljeretResultat")]
		public virtual bool VisDetaljeretResultat => this.Value<bool>(_publishedValueFallback, "visDetaljeretResultat");

		///<summary>
		/// HTML: HTML til at indsætte på ekstern hjemmeside. Dvs. side, som ikke er hostet hos os.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("html")]
		public virtual global::Newtonsoft.Json.Linq.JToken Html => global::DffEdb.Umb.Models.WebComponentHtml.GetHtml(this, _publishedValueFallback);
	}
}
