//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v11.4.1+29f8f0b
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace DffEdb.Umb.Models
{
	/// <summary>Tilslutningsanmodning Widget</summary>
	[PublishedModel("tilslutningsanmodningWidget")]
	public partial class TilslutningsanmodningWidget : PublishedContentModel, IWebComponentHtml
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		public new const string ModelTypeAlias = "tilslutningsanmodningWidget";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<TilslutningsanmodningWidget, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public TilslutningsanmodningWidget(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Overskrift
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("adresseOverskrift")]
		public virtual string AdresseOverskrift => this.Value<string>(_publishedValueFallback, "adresseOverskrift");

		///<summary>
		/// Tekst
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("adresseTekst")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString AdresseTekst => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "adresseTekst");

		///<summary>
		/// Afgræns til specifikke postnumre: Du har her mulighed for at afgrænse adressesøgningen til specifikke postnumre
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("afgraensningOverskrift")]
		public virtual string AfgraensningOverskrift => this.Value<string>(_publishedValueFallback, "afgraensningOverskrift");

		///<summary>
		/// Postnumre: Ét postnummer pr. linje.  Hvis du ikke angiver postnumre, søger vi i hele Danmark.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("afgraensningPostNr")]
		public virtual string AfgraensningPostNr => this.Value<string>(_publishedValueFallback, "afgraensningPostNr");

		///<summary>
		/// Alternativ email til tilslutninganmodning: Indtast e-mailadresse hvis du ønsker en anden end værkets e-mailadresse
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("alternativVaerksEmail")]
		public virtual string AlternativVaerksEmail => this.Value<string>(_publishedValueFallback, "alternativVaerksEmail");

		///<summary>
		/// E|Forsyning: Vælg hvilken E|Forsyning der skal kaldes for at undersøge om der leveres fjernvarme til en given adresse
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("eforsyningNodeId")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent EforsyningNodeId => this.Value<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent>(_publishedValueFallback, "eforsyningNodeId");

		///<summary>
		/// Vælg E|Forsyning: For at kunne undersøge om der leveres fjernvarme til en bestemt adresse, har vi behov for at lave opslag i FOF. Du skal derfor vælge en E|Forsyning, som har adgang til FOF.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("eforsyningOverskrift")]
		public virtual string EforsyningOverskrift => this.Value<string>(_publishedValueFallback, "eforsyningOverskrift");

		///<summary>
		/// Overskrift
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ejendomsfaktorerOverskrift")]
		public virtual string EjendomsfaktorerOverskrift => this.Value<string>(_publishedValueFallback, "ejendomsfaktorerOverskrift");

		///<summary>
		/// Tekst
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ejendomsfaktorerTekst")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString EjendomsfaktorerTekst => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "ejendomsfaktorerTekst");

		///<summary>
		/// Tekst
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("emailBody")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString EmailBody => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "emailBody");

		///<summary>
		/// E-mail: Ved fuldført interessetilkendegivelse sender vi en e-mail til værket og forbrugeren.   Du kan herunder angive emnefelt og hovedteksten i mailen.  Vi tilføjer automatisk oplysninger indtastet af forbrugeren samt værkets signatur.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("emailOverskrift")]
		public virtual string EmailOverskrift => this.Value<string>(_publishedValueFallback, "emailOverskrift");

		///<summary>
		/// Emne
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("emailSubject")]
		public virtual string EmailSubject => this.Value<string>(_publishedValueFallback, "emailSubject");

		///<summary>
		/// Knap: Hvis søgningen finder en passiv forbruger, giver vi mulighed for at vise interesse for fjernvarme. Det gøres ved en knap, hvor man har mulighed for at indsende oplysninger om sig selv og ejendommen.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("interesseKnapOverskrift")]
		public virtual string InteresseKnapOverskrift => this.Value<string>(_publishedValueFallback, "interesseKnapOverskrift");

		///<summary>
		/// Knap: Hvilken tekst skal der stå i knappen?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("interesseKnapTekst")]
		public virtual string InteresseKnapTekst => this.Value<string>(_publishedValueFallback, "interesseKnapTekst");

		///<summary>
		/// Overskrift
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("kvitteringOverskrift")]
		public virtual string KvitteringOverskrift => this.Value<string>(_publishedValueFallback, "kvitteringOverskrift");

		///<summary>
		/// Tekst
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("kvitteringTekst")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString KvitteringTekst => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "kvitteringTekst");

		///<summary>
		/// Overskrift
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("personligeOplysningerOverskrift")]
		public virtual string PersonligeOplysningerOverskrift => this.Value<string>(_publishedValueFallback, "personligeOplysningerOverskrift");

		///<summary>
		/// Tekst på send-knap: Standard: 'Send'
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("personligeOplysningerSendKnapTekst")]
		public virtual string PersonligeOplysningerSendKnapTekst => this.Value<string>(_publishedValueFallback, "personligeOplysningerSendKnapTekst");

		///<summary>
		/// Skjul feltet bemærkning
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("personligeOplysningerSkjulBemaerkning")]
		public virtual bool PersonligeOplysningerSkjulBemaerkning => this.Value<bool>(_publishedValueFallback, "personligeOplysningerSkjulBemaerkning");

		///<summary>
		/// Tekst
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("personligeOplysningerTekst")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString PersonligeOplysningerTekst => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "personligeOplysningerTekst");

		///<summary>
		/// Svarmuligheder: Nedenfor kan du angive hvilken tekst forbrugeren skal have vist, afhængig af om vi leverer fjernvarme til adressen eller ej
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("svarmulighederOverskrift")]
		public virtual string SvarmulighederOverskrift => this.Value<string>(_publishedValueFallback, "svarmulighederOverskrift");

		///<summary>
		/// Ja: Skriv tekst som skal vises, hvis der leveres fjernvarme til adressen
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("svarmulighedJa")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString SvarmulighedJa => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "svarmulighedJa");

		///<summary>
		/// Nej: Skriv tekst som skal vises, hvis der ikke levers fjernvarme til adressen
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("svarmulighedNej")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString SvarmulighedNej => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "svarmulighedNej");

		///<summary>
		/// Planlagt: Skriv tekst som skal vises, hvis der endnu ikke levers fjernvarme til adressen, men der er planer om det i nær fremtid.  Bemærk, at denne tekst kan overstyres vha. ejendomsfaktorer i FOF, så man kan have forskellig tekst afhængig af, hvornår der er planlagt fjernvarme på en adresse.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("svarmulighedPlanlagt")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString SvarmulighedPlanlagt => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "svarmulighedPlanlagt");

		///<summary>
		/// Vis e-Boks tilmelding: Skal der vises felter, som giver mulighed for at tilmelde sig post via e-Boks?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("visEBoksTilmelding")]
		public virtual bool VisEboksTilmelding => this.Value<bool>(_publishedValueFallback, "visEBoksTilmelding");

		///<summary>
		/// HTML: HTML til at indsætte på ekstern hjemmeside. Dvs. side, som ikke er hostet hos os.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("html")]
		public virtual global::Newtonsoft.Json.Linq.JToken Html => global::DffEdb.Umb.Models.WebComponentHtml.GetHtml(this, _publishedValueFallback);
	}
}
