//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v11.4.1+29f8f0b
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace DffEdb.Umb.Models
{
	/// <summary>Vaerk</summary>
	[PublishedModel("vaerk")]
	public partial class Vaerk : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		public new const string ModelTypeAlias = "vaerk";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<Vaerk, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Vaerk(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Åbningstider
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("abningstider")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel Abningstider => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "abningstider");

		///<summary>
		/// Bankkonto
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bankkonto")]
		public virtual string Bankkonto => this.Value<string>(_publishedValueFallback, "bankkonto");

		///<summary>
		/// Box indhold 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("boxIndhold1")]
		public virtual string BoxIndhold1 => this.Value<string>(_publishedValueFallback, "boxIndhold1");

		///<summary>
		/// Box indhold 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("boxIndhold2")]
		public virtual string BoxIndhold2 => this.Value<string>(_publishedValueFallback, "boxIndhold2");

		///<summary>
		/// Box indhold 3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("boxIndhold3")]
		public virtual string BoxIndhold3 => this.Value<string>(_publishedValueFallback, "boxIndhold3");

		///<summary>
		/// Brødtekst
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("broedtekst")]
		public virtual global::Newtonsoft.Json.Linq.JToken Broedtekst => this.Value<global::Newtonsoft.Json.Linq.JToken>(_publishedValueFallback, "broedtekst");

		///<summary>
		/// Farveskema
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("colourScheme")]
		public virtual global::Newtonsoft.Json.Linq.JToken ColourScheme => this.Value<global::Newtonsoft.Json.Linq.JToken>(_publishedValueFallback, "colourScheme");

		///<summary>
		/// Custom farve
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("customFarve")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel CustomFarve => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "customFarve");

		///<summary>
		/// EAN
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("eAN")]
		public virtual string EAN => this.Value<string>(_publishedValueFallback, "eAN");

		///<summary>
		/// Logo: Logo på e-mails sendt via Umbraco.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("emailLogo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops EmailLogo => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "emailLogo");

		///<summary>
		/// Signatur: Signatur på e-mails sendt via Umbraco
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("emailSignatur")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString EmailSignatur => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "emailSignatur");

		///<summary>
		/// Facebook domæneverificering: Indeholder typisk 30 karakter
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("facebookDomainVerification")]
		public virtual string FacebookDomainVerification => this.Value<string>(_publishedValueFallback, "facebookDomainVerification");

		///<summary>
		/// Facebook Pixel: Her kan du indsætte Facebook Pixel Id
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("facebookPixel")]
		public virtual string FacebookPixel => this.Value<string>(_publishedValueFallback, "facebookPixel");

		///<summary>
		/// Farver
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("farver")]
		public virtual object Farver => this.Value(_publishedValueFallback, "farver");

		///<summary>
		/// Cookiepolitik: Ved blank værdi følges opsætning under Global Settings
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("featureToggleCookiepolitik")]
		public virtual string FeatureToggleCookiepolitik => this.Value<string>(_publishedValueFallback, "featureToggleCookiepolitik");

		///<summary>
		/// Adresse
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("firmaAdresse")]
		public virtual string FirmaAdresse => this.Value<string>(_publishedValueFallback, "firmaAdresse");

		///<summary>
		/// By
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("firmaBy")]
		public virtual string FirmaBy => this.Value<string>(_publishedValueFallback, "firmaBy");

		///<summary>
		/// CVR / SE
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("firmaCvrSe")]
		public virtual string FirmaCvrSe => this.Value<string>(_publishedValueFallback, "firmaCvrSe");

		///<summary>
		/// E-Mail
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("firmaEmail")]
		public virtual string FirmaEmail => this.Value<string>(_publishedValueFallback, "firmaEmail");

		///<summary>
		/// Land
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("firmaLand")]
		public virtual string FirmaLand => this.Value<string>(_publishedValueFallback, "firmaLand");

		///<summary>
		/// Firmanavn
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("firmaNavn")]
		public virtual string FirmaNavn => this.Value<string>(_publishedValueFallback, "firmaNavn");

		///<summary>
		/// Firmaoplysninger
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("firmaoplysninger")]
		public virtual object Firmaoplysninger => this.Value(_publishedValueFallback, "firmaoplysninger");

		///<summary>
		/// Postnr
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("firmaPostnr")]
		public virtual string FirmaPostnr => this.Value<string>(_publishedValueFallback, "firmaPostnr");

		///<summary>
		/// Telefonnr
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("firmaTlf")]
		public virtual string FirmaTlf => this.Value<string>(_publishedValueFallback, "firmaTlf");

		///<summary>
		/// Web
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("firmaWeb")]
		public virtual string FirmaWeb => this.Value<string>(_publishedValueFallback, "firmaWeb");

		///<summary>
		/// Fonte
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fonte")]
		public virtual object Fonte => this.Value(_publishedValueFallback, "fonte");

		///<summary>
		/// Forsyningsid
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("forsyningId")]
		public virtual string ForsyningId => this.Value<string>(_publishedValueFallback, "forsyningId");

		///<summary>
		/// Google Analytics 4: Format: G-xxxxxxxxxx  Indsæt Google Analytics 4 sporings-id, som gælder for hjemmeside og alle E|Forsyninger
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ga4MeasurementId")]
		public virtual string Ga4MeasurementId => this.Value<string>(_publishedValueFallback, "ga4MeasurementId");

		///<summary>
		/// Google Universal Analytics (udgår): Format: UA-xxxxxxxxxx  Indsæt Universal Analytics sporings-id, som gælder for hjemmeside og alle E|Forsyninger
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("googleAnalytics")]
		public virtual string GoogleAnalytics => this.Value<string>(_publishedValueFallback, "googleAnalytics");

		///<summary>
		/// Google site verification: Her kan du tilføje kode for "google-site-verification"
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("googleSiteVerification")]
		public virtual string GoogleSiteVerification => this.Value<string>(_publishedValueFallback, "googleSiteVerification");

		///<summary>
		/// Kontaktperson Cookiepolitik
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("kontaktpersonCookiepolitik")]
		public virtual string KontaktpersonCookiepolitik => this.Value<string>(_publishedValueFallback, "kontaktpersonCookiepolitik");

		///<summary>
		/// Link farve: Farven på links
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("linkFarve")]
		public virtual object LinkFarve => this.Value(_publishedValueFallback, "linkFarve");

		///<summary>
		/// Link til Facebook
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("linkTilFacebook")]
		public virtual string LinkTilFacebook => this.Value<string>(_publishedValueFallback, "linkTilFacebook");

		///<summary>
		/// Link til Google+
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("linkTilGoogle")]
		public virtual string LinkTilGoogle => this.Value<string>(_publishedValueFallback, "linkTilGoogle");

		///<summary>
		/// Link til Instagram
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("linkTilInstagram")]
		public virtual string LinkTilInstagram => this.Value<string>(_publishedValueFallback, "linkTilInstagram");

		///<summary>
		/// Link til LinkedIn
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("linkTilLinkedIn")]
		public virtual string LinkTilLinkedIn => this.Value<string>(_publishedValueFallback, "linkTilLinkedIn");

		///<summary>
		/// Logo: Vælg logo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("logo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops Logo => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "logo");

		///<summary>
		/// Menu
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("menu")]
		public virtual global::Newtonsoft.Json.Linq.JToken Menu => this.Value<global::Newtonsoft.Json.Linq.JToken>(_publishedValueFallback, "menu");

		///<summary>
		/// Menu i versaler
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("menuIVersaler")]
		public virtual bool MenuIversaler => this.Value<bool>(_publishedValueFallback, "menuIVersaler");

		///<summary>
		/// Overskrifter
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("overskrifter")]
		public virtual global::Newtonsoft.Json.Linq.JToken Overskrifter => this.Value<global::Newtonsoft.Json.Linq.JToken>(_publishedValueFallback, "overskrifter");

		///<summary>
		/// Åbningstider
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("seperatorabningstider")]
		public virtual object Seperatorabningstider => this.Value(_publishedValueFallback, "seperatorabningstider");

		///<summary>
		/// Sociale medier
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("socialeMedier")]
		public virtual object SocialeMedier => this.Value(_publishedValueFallback, "socialeMedier");

		///<summary>
		/// Tekst farver
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tekstFarver")]
		public virtual object TekstFarver => this.Value(_publishedValueFallback, "tekstFarver");

		///<summary>
		/// Vagttelefon
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("vagttelefon")]
		public virtual string Vagttelefon => this.Value<string>(_publishedValueFallback, "vagttelefon");

		///<summary>
		/// Vis driftsstatus: Skal driftsstatus vises i toppen af siden?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "11.4.1+29f8f0b")]
		[ImplementPropertyType("visDriftsstatus")]
		public virtual bool VisDriftsstatus => this.Value<bool>(_publishedValueFallback, "visDriftsstatus");
	}
}
